In [229]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [239]:
Daegu_Buk_gu_cctv = pd.read_csv('./Daegu_Buk_gu.csv', encoding='utf-8')
Daegu_Dalseo_gu_cctv = pd.read_csv('./Daegu_Dalseo_gu.csv', encoding='utf-8')
Daegu_Dalseong_gun_cctv = pd.read_csv('./Daegu_Dalseong_gun.csv', encoding='utf-8')
Daegu_Dong_gu_cctv = pd.read_csv('./Daegu_Dong_gu.csv', encoding='utf-8')
Daegu_Jung_gu_cctv = pd.read_csv('./Daegu_Jung_gu.csv', encoding='utf-8')
Daegu_Nam_gu_cctv = pd.read_csv('./Daegu_Nam_gu.csv', encoding='utf-8')
Daegu_Seo_gu_cctv = pd.read_csv('./Daegu_Seo_gu.csv', encoding='utf-8')
Daegu_Suseong_gu_cctv = pd.read_csv('./Daegu_Suseong_gu.csv', encoding='utf-8')

Daegu_cctv = pd.read_csv('./Daegu.csv', encoding='utf-8')
Daegu_population = pd.read_csv('./Daegu_population.csv', encoding='utf-8')

local_name_list = ['북구','달서구','달성군','동구','중구','남구','서구','수성구']

cctv_list = [
    Daegu_Buk_gu_cctv, Daegu_Dalseo_gu_cctv, Daegu_Dalseong_gun_cctv, 
    Daegu_Dong_gu_cctv, Daegu_Jung_gu_cctv, Daegu_Nam_gu_cctv,
    Daegu_Seo_gu_cctv, Daegu_Suseong_gu_cctv
            ]

In [240]:
cctv_num_list =[]
for num in cctv_list:
    cctv_num_list.append(num['카메라대수'].sum())
cctv_num_list

[1617, 1409, 1048, 1294, 741, 708, 662, 1404]

In [241]:
row_data = {
    '지역': local_name_list,
    '카메라대수': cctv_num_list       
}
local_cctv_num = pd.DataFrame(row_data, columns=['지역','카메라대수'])
local_cctv_num = local_cctv_num.set_index('지역')

In [242]:
list_daegu_cctv_Separation = []

for local_name in local_name_list:
    list_daegu_cctv_Separation.append(Daegu_cctv[Daegu_cctv['소재지지번주소'].str.find(local_name) > 0]['카메라대수'].sum())
list_daegu_cctv_Separation

[32, 64, 20, 64, 41, 22, 92, 36]

In [243]:
cctv_num = local_cctv_num['카메라대수'].values + list_daegu_cctv_Separation
cctv_num

array([1649, 1473, 1068, 1358,  782,  730,  754, 1440], dtype=int64)

In [244]:
local_cctv_num['카메라대수'] = cctv_num

In [245]:
local_cctv_num
Daegu_population

,행정구역,총계,총계 남,총계 여,중구 계,중구 남,중구 여,동구 계,동구 남,동구 여,...,북구 여,수성구 계,수성구 남,수성구 여,달서구 계,달서구 남,달서구 여,달성군 계,달성군 남,달성군 여
0,0세,"13,085","6,754","6,331",456,228,228,"2,019","1,021",998,...,"1,221","1,565",839,726,"2,771","1,413","1,358","2,660","1,358","1,302"
1,1세,"15,384","7,854","7,530",524,273,251,"2,401","1,235","1,166",...,"1,434","1,964",986,978,"3,370","1,780","1,590","2,885","1,429","1,456"
2,2세,"17,580","9,026","8,554",588,293,295,"2,718","1,429","1,289",...,"1,682","2,387","1,217","1,170","3,836","2,028","1,808","3,138","1,579","1,559"
3,3세,"19,659","10,028","9,631",625,325,300,"2,947","1,442","1,505",...,"1,848","2,839","1,501","1,338","4,480","2,313","2,167","3,362","1,701","1,661"
4,4세,"20,230","10,294","9,936",628,297,331,"3,103","1,620","1,483",...,"1,858","3,069","1,536","1,533","4,710","2,388","2,322","3,260","1,641","1,619"
5,5세,"19,869","10,102","9,767",542,279,263,"2,936","1,506","1,430",...,"1,868","3,269","1,690","1,579","4,597","2,326","2,271","3,033","1,514","1,519"
6,6세,"21,284","10,954","10,330",588,306,282,"2,992","1,547","1,445",...,"1,949","3,779","1,946","1,833","4,927","2,522","2,405","3,174","1,682","1,492"
7,7세,"21,931","11,164","10,767",553,290,263,"3,067","1,577","1,490",...,"1,979","4,096","2,092","2,004","5,213","2,600","2,613","3,135","1,584","1,551"
8,8세,"22,163","11,457","10,706",583,302,281,"2,991","1,562","1,429",...,"1,959","4,302","2,209","2,093","5,313","2,749","2,564","3,018","1,541","1,477"
9,9세,"20,331","10,565","9,766",485,262,223,"2,763","1,462","1,301",...,"1,807","4,106","2,128","1,978","5,019","2,607","2,412","2,628","1,375","1,253"
10,10세,"20,872","10,817","10,055",473,254,219,"2,723","1,418","1,305",...,"1,904","4,407","2,318","2,089","5,043","2,648","2,395","2,537","1,280","1,257"
11,11세,"22,716","11,700","11,016",504,256,248,"2,868","1,423","1,445",...,"2,042","5,104","2,645","2,459","5,501","2,849","2,652","2,551","1,317","1,234"
12,12세,"21,529","11,129","10,400",433,229,204,"2,585","1,354","1,231",...,"1,987","5,002","2,600","2,402","5,159","2,645","2,514","2,335","1,199","1,136"
13,13세,"20,989","10,983","10,006",463,239,224,"2,380","1,264","1,116",...,"1,954","4,977","2,641","2,336","5,160","2,650","2,510","2,160","1,136","1,024"
14,14세,"21,678","11,321","10,357",441,206,235,"2,599","1,370","1,229",...,"2,021","5,028","2,695","2,333","5,339","2,787","2,552","2,172","1,105","1,067"
15,15세,"23,729","12,498","11,231",528,252,276,"2,622","1,391","1,231",...,"2,178","5,638","2,985","2,653","5,870","3,055","2,815","2,139","1,139","1,000"
16,16세,"24,137","12,817","11,320",567,298,269,"2,798","1,453","1,345",...,"2,165","5,570","3,039","2,531","6,034","3,130","2,904","2,204","1,200",1004
17,17세,"25,844","13,706","12,138",556,285,271,"2,962","1,591","1,371",...,"2,402","5,893","3,120","2,773","6,502","3,402","3,100","2,235","1,211","1,024"
18,18세,"30,212","15,919","14,293",648,329,319,"3,416","1,778","1,638",...,"2,802","6,827","3,684","3,143","7,754","4,055","3,699","2,591","1,367","1,224"
19,19세,"31,521","16,721","14,800",757,357,400,"3,676","2,027","1,649",...,"2,917","6,644","3,572","3,072","8,194","4,308","3,886","2,697","1,442","1,255"
20,20세,"30,450","16,303","14,147",809,390,419,"3,632","1,982","1,650",...,"2,772","6,222","3,386","2,836","7,925","4,279","3,646","2,592","1,416","1,176"
21,21세,"33,233","17,532","15,701",902,422,480,"4,016","2,173","1,843",...,"3,054","6,533","3,487","3,046","8,540","4,510","4,030","2,851","1,532","1,319"
22,22세,"34,437","18,122","16,315","1,089",519,570,"4,237","2,162","2,075",...,"3,128","6,429","3,462","2,967","8,627","4,498","4,129","2,956","1,636","1,320"
23,23세,"35,101","18,816","16,285","1,151",525,626,"4,435","2,360","2,075",...,"3,045","6,376","3,451","2,925","8,861","4,679","4,182","2,912","1,699","1,213"
24,24세,"34,230","18,638","15,592","1,325",642,683,"4,357","2,355","2,002",...,"2,870","5,980","3,295","2,685","8,592","4,652","3,940","2,856","1,634","1,222"
25,25세,"34,350","18,834","15,516","1,277",641,636,"4,560","2,515","2,045",...,"2,795","5,822","3,138","2,684","8,560","4,715","3,845","2,960","1,647","1,313"
26,26세,"33,823","18,416","15,407","1,370",669,701,"4,548","2,426","2,122",...,"2,620","5,466","3,009","2,457","8,429","4,566","3,863","3,088","1,719","1,369"
27,27세,"33,142","18,053","15,089","1,304",668,636,"4,638","2,542","2,096",...,"2,579","5,206","2,792","2,414","8,063","4,356","3,707","3,216","1,741","1,475"
28,28세,"29,575","15,963","13,612","1,221",626,595,"4,142","2,241","1,901",...,"2,415","4,546","2,391","2,155","7,133","3,964","3,169","3,003","1,578","1,425"
29,29세,"29,455","16,060","13,395","1,172",612,560,"4,268","2,386","1,882",...,"2,393","4,407","2,367","2,040","7,132","3,890","3,242","3,331","1,825","1,506"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,71세,"21,018","9,533","11,485",887,391,496,"3,585","1,628","1,957",...,"1,873","3,434","1,552","1,882","4,189","1,948","2,241","1,663",807,856
72,72세,"19,430","8,632","10,798",864,368,496,"3,344","1,471","1,873",...,"1,672","3,237","1,402","1,835","3,821","1,769","2,052","1,442",677,765
73,73세,"11,818","5,392","6,426",543,221,322,"2,073",939,"1,134",...,"1,037","1,920",896,"1,024","2,281","1,075","1,206",957,474,483
74,74세,"15,082","6,500","8,582",661,275,386,"2,672","1,130","1,542",...,"1,463","2,526","1,092","1,434","2,851","1,269","1,582","1,125",530,595
75,75세,"16,042","6,664","9,378",791,335,456,"2,796","1,181","1,615",...,"1,534","2,735","1,177","1,558","2,932","1,197","1,735","1,162",478,684
76,76세,"17,920","7,638","10,282",803,349,454,"3,058","1,298","1,760",...,"1,658","3,026","1,290","1,736","3,375","1,457","1,918","1,354",581,773
77,77세,"16,730","7,078","9,652",753,354,399,"2,886","1,199","1,687",...,"1,570","2,726","1,163","1,563","3,158","1,311","1,847","1,227",482,745
78,78세,"13,966","5,569","8,397",600,241,359,"2,446",1025,"1,421",...,"1,332","2,339",957,"1,382","2,626",1040,"1,586","1,108",394,714
79,79세,"12,994","5,051","7,943",585,228,357,"2,272",912,"1,360",...,"1,327","2,209",905,"1,304","2,391",899,"1,492",979,330,649
80,80세,"12,017","4,702","7,315",545,210,335,"2,009",794,"1,215",...,"1,127","2,020",796,"1,224","2,268",847,"1,421",933,336,597
81,81세,"10,451","3,869","6,582",470,171,299,"1,763",644,"1,119",...,987,"1,891",735,"1,156","1,987",718,"1,269",841,316,525
82,82세,"9,634","3,541","6,093",444,172,272,"1,626",610,"1,016",...,954,"1,698",653,"1,045","1,845",652,"1,193",790,273,517
83,83세,"8,747","3,052","5,695",381,161,220,"1,466",532,934,...,841,"1,612",568,"1,044","1,724",540,"1,184",643,220,423
84,84세,"7,651","2,663","4,988",333,127,206,"1,264",435,829,...,800,"1,462",532,930,"1,399",494,905,619,181,438
85,85세,"6,287","2,021","4,266",272,92,180,"1,024",328,696,...,673,"1,180",408,772,"1,211",383,828,514,145,369
86,86세,"5,213","1,621","3,592",213,62,151,834,270,564,...,571,"1,029",327,702,955,276,679,449,152,297
87,87세,"4,388","1,295","3,093",204,59,145,705,230,475,...,483,824,255,569,845,234,611,357,107,250
88,88세,"3,309",840,"2,469",157,39,118,505,135,370,...,365,644,186,458,620,153,467,292,68,224
89,89세,"2,578",608,"1,970",118,27,91,418,110,308,...,307,506,136,370,499,121,378,210,36,174
90,90세,"2,218",545,"1,673",113,32,81,305,83,222,...,247,451,101,350,440,107,333,161,36,125
91,91세,"1,746",407,"1,339",102,30,72,293,66,227,...,184,333,72,261,310,68,242,151,37,114
92,92세,"1,325",284,"1,041",72,13,59,231,44,187,...,146,246,64,182,220,49,171,131,21,110
93,93세,874,174,700,48,14,34,135,23,112,...,100,170,37,133,155,28,127,75,15,60
94,94세,696,150,546,36,9,27,128,26,102,...,77,131,30,101,127,28,99,55,14,41
95,95세,428,86,342,31,9,22,89,11,78,...,36,76,17,59,79,20,59,27,5,22
96,96세,424,91,333,28,7,21,56,12,44,...,69,67,20,47,77,17,60,36,7,29
97,97세,292,62,230,19,2,17,64,11,53,...,32,54,12,42,46,9,37,20,7,13
98,98세,191,31,160,16,2,14,29,10,19,...,30,32,3,29,30,4,26,11,1,10
99,99세,152,26,126,16,7,9,27,6,21,...,23,25,3,22,17,4,13,8,0,8
100,100세 이상,650,153,497,87,16,71,115,29,86,...,59,95,27,68,79,15,64,28,8,20

In [251]:
Daegu_population['행정구역']=Daegu_population['행정구역'].str.replace('세','')
Daegu_population['행정구역']=Daegu_population['행정구역'].str.replace(' 이상','')

In [252]:
Daegu_population = Daegu_population.applymap(lambda x:str(x).replace(',',''))
Daegu_population = Daegu_population.applymap(lambda x:int(str(x)))

In [253]:
Daegu_population.columns.str.replace(' ','')

Index(['행정구역', '총계', '총계남', '총계여', '중구계', '중구남', '중구여', '동구계', '동구남', '동구여',
       '서구계', '서구남', '서구여', '남구계', '남구남', '남구여', '북구계', '북구남', '북구여', '수성구계',
       '수성구남', '수성구여', '달서구계', '달서구남', '달서구여', '달성군계', '달성군남', '달성군여'],
      dtype='object')

In [254]:
Daegu_population.columns = Daegu_population.columns.str.replace(' ','')

In [256]:
Daegu_population.head()

,행정구역,총계,총계남,총계여,중구계,중구남,중구여,동구계,동구남,동구여,...,북구여,수성구계,수성구남,수성구여,달서구계,달서구남,달서구여,달성군계,달성군남,달성군여
0,0,13085,6754,6331,456,228,228,2019,1021,998,...,1221,1565,839,726,2771,1413,1358,2660,1358,1302
1,1,15384,7854,7530,524,273,251,2401,1235,1166,...,1434,1964,986,978,3370,1780,1590,2885,1429,1456
2,2,17580,9026,8554,588,293,295,2718,1429,1289,...,1682,2387,1217,1170,3836,2028,1808,3138,1579,1559
3,3,19659,10028,9631,625,325,300,2947,1442,1505,...,1848,2839,1501,1338,4480,2313,2167,3362,1701,1661
4,4,20230,10294,9936,628,297,331,3103,1620,1483,...,1858,3069,1536,1533,4710,2388,2322,3260,1641,1619

In [269]:
# local_cctv_num
people_num = Daegu_population.sum()

In [268]:
# local_cctv_num.columns
local_name_list
data = {
    '총인원': [],
    '남': [],
    '여':[]
}
local_cctv_num = pd.DataFrame(data, columns=['총인원','남','여'])
local_cctv_num = local_cctv_num.set_index('지역')

['북구', '달서구', '달성군', '동구', '중구', '남구', '서구', '수성구']